- name: Set HostName
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy Nginx Config File
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy RoboShop Config File
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Import Common Role - App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend
    app_user: root

- name: Start nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Import ELK Role - Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus - Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

- name: Install New Relic Agent
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY={{ lookup('amazon.aws.aws_ssm', 'newrelic.key', region='us-east-1' ) }} NEW_RELIC_ACCOUNT_ID=4094457 /usr/local/bin/newrelic install -y -n infrastructure-agent-installer --tag {{component}}-{{env}}

- name: Install New Relic Nginx Agent
  ansible.builtin.dnf:
    name: nri-nginx
    state: installed

- name: Copy New Relic Nginx Agent Config File
  ansible.builtin.template:
    src: nr-nginx.yml
    dest: /etc/newrelic-infra/integrations.d/nginx-config.yml

- name: Copy New Relic Nginx Agent Log Shipper Config File
  ansible.builtin.template:
    src: nr-nginx-log.yml
    dest: /etc/newrelic-infra/logging.d/nginx-log.yml

