- name: Check GoLang
  ansible.builtin.shell: type go
  ignore_errors: yes
  register: go_stat

- name: Install Golang
  ansible.builtin.dnf:
    name: golang
    state: present
  when: go_stat.rc != 0

- name: Import Common Role - App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: Import SystemD
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: Download GoLang Dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ;  go build
  args:
    chdir: "{{app_dir}}"

- name: Import Schema
  ansible.builtin.import_role:
    name: common
    tasks_from: schema-load
  when: schema_needed

- name: Import Observability
  ansible.builtin.import_role:
    name: common
    tasks_from: observability

