- name: Set HostName
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Import ELK Role - Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus - Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter



