- name: MongoDB Schema Load
  when: schema_type == "mongo"
  block:
    - name: Copy MongoDB repo file
      ansible.builtin.template:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install Mongo Client
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema:
      ansible.builtin.shell: mongo --ssl --host {{ENDPOINT}} --sslCAFile /app/rds-combined-ca-bundle.pem --username {{USERNAME}} --password {{PASSWORD}}
      vars:
        ENDPOINT: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{project_name}}.catalogue.DOCDB_ENDPOINT', region='us-east-1' ) }}:27017"
        USERNAME: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{project_name}}.docdb.username', region='us-east-1' ) }}"
        PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{project_name}}.docdb.password', region='us-east-1' ) }}"

- name: MySQL Schema Load
  when: schema_type == "mysql"
  block:
    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql
        state: installed

    ## Load Schema - TBD
    #- name: Load Schema:
    #  ansible.builtin.shell: mysql
